services:
  mysql:
    image: mariadb
    restart: always
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'admin'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'hr'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
    volumes:
      - ./migration/init:/docker-entrypoint-initdb.d
      - ./dump:/tmp/dump